/*
 * SOCreateProcessPanel.java
 *
 * Created on 14 de Maio de 2008, 19:27
 */

package com.solab.ui;

import com.solab.so.SO;
import com.solab.so.SOProcess;
import com.solab.so.SOProcessFactory;

/**
 * $Id: SOCreateProcessPanel.java,v 1.3 2008/05/25 18:41:50 Mayko Exp $
 *
 * @author Mayko Sartor - <a
 *         href="mailto:maykosartor@gmail.com">maykosartor@gmail.com </a><br>
 */
public class SOCreateProcessPanel extends javax.swing.JPanel {

    private SO so;
    
    /** Creates new form SOCreateProcessPanel */
    public SOCreateProcessPanel() {
        initComponents();
    }

    public SO getSo() {
        return so;
    }

    public void setSo(SO so) {
        this.so = so;
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPriori = new javax.swing.JLabel();
        spPri = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        spFra = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jxTipo = new javax.swing.JComboBox();
        btnCriar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        spQua = new javax.swing.JSpinner();
        btnCriarRan = new javax.swing.JButton();

        lblPriori.setText("Prioridade");

        spPri.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        jLabel1.setText("Páginas");

        spFra.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));

        jLabel2.setText("Tipo");

        jxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mais CPU", "Mais Entrada/Saída", "Ambos" }));

        btnCriar.setText("Criar Processos");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade");

        spQua.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        btnCriarRan.setText("Criar Processos Aleatórios");
        btnCriarRan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarRanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPriori)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jxTipo, 0, 270, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(spPri, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spFra, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102))))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(spQua, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCriarRan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCriar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriori)
                    .addComponent(spFra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(spPri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriar)
                    .addComponent(btnCriarRan))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
    int qua = (Integer) spQua.getValue();
    int type = jxTipo.getSelectedIndex() + 1;
    int pri = (Integer) spPri.getValue();
    int max = (Integer) spFra.getValue();
    
    for (int i = 0; i < qua; i++) {
        
        SOProcess proc = SOProcessFactory.getInstance().createProcess(type, pri, max);
        
        this.so.createProcess(proc);        
    }        
}//GEN-LAST:event_btnCriarActionPerformed

private void btnCriarRanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarRanActionPerformed
    int qua = (Integer) spQua.getValue();
    
    for (int i = 0; i < qua; i++) {
        SOProcess proc = SOProcessFactory.getInstance().createProcess();
        
        this.so.createProcess(proc);        
    }     
}//GEN-LAST:event_btnCriarRanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnCriarRan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox jxTipo;
    private javax.swing.JLabel lblPriori;
    private javax.swing.JSpinner spFra;
    private javax.swing.JSpinner spPri;
    private javax.swing.JSpinner spQua;
    // End of variables declaration//GEN-END:variables

}
