/*
 * SOCreateProcessFrame.java
 *
 * Created on 18 de Maio de 2008, 18:24
 */
package com.solab.ui;

import com.solab.so.SO;

/**
 * $Id: SOCreateProcessFrame.java,v 1.2 2008/05/25 18:41:50 Mayko Exp $
 *
 * @author Mayko Sartor - <a
 *         href="mailto:maykosartor@gmail.com">maykosartor@gmail.com </a><br>
 */
public class SOCreateProcessFrame extends javax.swing.JFrame {

    private SO so;
    
    /** Creates new form SOCreateProcessFrame */
    public SOCreateProcessFrame() {
        initComponents();
    }

    public SO getSo() {
        return so;
    }

    public void setSo(SO so) {
        this.so = so;
        
        this.soCreateProcessPanel.setSo(so);
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soCreateProcessPanel = new com.solab.ui.SOCreateProcessPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Processos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(soCreateProcessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(soCreateProcessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.solab.ui.SOCreateProcessPanel soCreateProcessPanel;
    // End of variables declaration//GEN-END:variables
}
