/*
 * SOMemoryFrame.java
 *
 * Created on 7 de Maio de 2008, 19:42
 */
package com.solab.ui;

import com.solab.model.event.SOEvent;
import com.solab.model.event.SOListener;
import com.solab.model.event.SOMemoryEvent;
import com.solab.model.event.SOMemoryListener;
import com.solab.so.SO;

/**
 * $Id: SOMemoryFrame.java,v 1.2 2008/05/18 21:27:41 Mayko Exp $
 *
 * @author Mayko Sartor - <a
 *         href="mailto:maykosartor@gmail.com">maykosartor@gmail.com </a><br>
 */
public class SOMemoryFrame extends javax.swing.JFrame implements SOListener, SOMemoryListener {

    private SO so;

    /** Creates new form SOMemoryFrame */
    public SOMemoryFrame() {
        initComponents();        
    }

    public SO getSo() {
        return so;
    }

    public void setSo(SO so) {
        this.so = so;
        this.soMemoryPanel.setSo(so);
        this.so.getSoMemory().addSOMemoryListener(this);
        this.so.getSoMemory().addSOMemoryListener(this.soMemoryPanel);
    }  
    
    public void soStarted(SOEvent e) {
        
    }

    public void processQueueInitialized(SOEvent e) {
        
    }

    public void schedulerInitialized(SOEvent e) {
        
    }

    public void memoryInitialized(SOEvent e) {
        this.so.getSoMemory().addSOMemoryListener(this);
        this.so.getSoMemory().addSOMemoryListener(this.soMemoryPanel);
    }
    
    public void memoryChanged(SOMemoryEvent e) {        
        this.txtPagMem.setText(String.valueOf(this.so.getSoMemory().getVirtualMemorySize()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soMemoryPanel = new com.solab.ui.SOMemoryPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPagMem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerência de Memória");

        javax.swing.GroupLayout soMemoryPanelLayout = new javax.swing.GroupLayout(soMemoryPanel);
        soMemoryPanel.setLayout(soMemoryPanelLayout);
        soMemoryPanelLayout.setHorizontalGroup(
            soMemoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        soMemoryPanelLayout.setVerticalGroup(
            soMemoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Quantidade Páginas Memória Virtual");

        txtPagMem.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPagMem, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPagMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(soMemoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(soMemoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.solab.ui.SOMemoryPanel soMemoryPanel;
    private javax.swing.JTextField txtPagMem;
    // End of variables declaration//GEN-END:variables
    
}
