/*
 * SOProcessFrame.java
 *
 * Created on 25 de Maio de 2008, 14:53
 */

package com.solab.ui;

import com.solab.so.SO;

/**
 * $Id: SOProcessFrame.java,v 1.3 2008/06/16 13:22:55 Mayko Exp $
 *
 * @author Mayko Sartor - <a
 *         href="mailto:maykosartor@gmail.com">maykosartor@gmail.com </a><br>
 */
public class SOProcessFrame extends javax.swing.JFrame {

    private SO so;
    
    /** Creates new form SOProcessFrame */
    public SOProcessFrame() {
        initComponents();
    }

    public SO getSo() {
        return so;
    }

    public void setSo(SO so) {
        this.so = so;
        this.soProcPanel.setSo(so);
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soProcPanel = new com.solab.ui.SOProcessPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Processos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(soProcPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(soProcPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.solab.ui.SOProcessPanel soProcPanel;
    // End of variables declaration//GEN-END:variables

}
